branches:
  only:
  - master
  - WIP

language: cpp

compiler:
  - g++

os:
  - linux

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8 g++-4.8-multilib linux-libc-dev linux-libc-dev:i386
  - sudo apt-get install python3 python3-pip
  - sudo pip3 install --upgrade pip
  - sudo pip3 install conan

before_script:
  - mkdir build
  - cd build
  - conan install .. --profile ../conan_profiles/gcc6.2_debug_x64.txt --build missing

script:
  - cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-m64"
  - cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-m64"
  - cmake --build . --config Debug
  - ctest --output-on-failure
